source 'http://rubygems.org'

gem 'rails', '3.1.1'
gem 'pg', '0.11.0'

gem 'haml-rails'
gem 'haml'
gem 'simple_form'
gem 'inherited_resources'



# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :test, :development do
  gem 'nifty-generators'
  gem 'rspec-rails',      '2.7.0'
end

gem "mocha", :group => :test
