development:
  adapter: postgresql
  encoding: unicode
  database: sem_pg_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sem_pg_test
  pool: 5
  username:
  password:
