######################################################################
##
## Filename: decoder_decoder_sch_tb.udo
## Created on: Mon Nov 07 15:19:43 Środkowoeuropejski czas stand. 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
