######################################################################
##
## Filename: counter_counter_sch_tb.udo
## Created on: Mon Nov 07 14:55:09 Środkowoeuropejski czas stand. 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
