######################################################################
##
## Filename: ps2test.udo
## Created on: Mon Dec 12 15:30:13 Środkowoeuropejski czas stand. 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
