######################################################################
##
## Filename: lab4_lab4_sch_tb.udo
## Created on: Mon Oct 17 15:31:50 Środkowoeuropejski czas letni 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
