######################################################################
##
## Filename: zad1_zad1_sch_tb.udo
## Created on: Mon Oct 03 14:58:10 Środkowoeuropejski czas letni 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
