---
webapp: ec2-23-20-42-58.compute-1.amazonaws.com
webapi:
- ec2-184-73-145-55.compute-1.amazonaws.com
- ec2-23-21-17-52.compute-1.amazonaws.com
- ec2-23-22-27-64.compute-1.amazonaws.com
- ec2-23-20-82-146.compute-1.amazonaws.com
- ec2-107-21-171-178.compute-1.amazonaws.com
- ec2-50-16-27-147.compute-1.amazonaws.com
- ec2-107-22-13-165.compute-1.amazonaws.com
- ec2-184-73-125-178.compute-1.amazonaws.com
workers:
- stopped
- stopped
- stopped
- stopped
