######################################################################
##
## Filename: zad2_zad2_sch_tb.udo
## Created on: Mon Oct 03 16:03:17 Środkowoeuropejski czas letni 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
