######################################################################
##
## Filename: counter1test.udo
## Created on: Mon Nov 21 15:31:12 Środkowoeuropejski czas stand. 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
